version: '3.8'

name: market-monitoring-service
services:
  market-monitoring:
    container_name: market-monitoring
    build: .
    entrypoint: ["/bin/sh", "-c", "exec ./run.sh"]
    ipc: host
    tty: true
    volumes:
      - .env:/app/.env
      - ./logs/:/app/logs
    networks:
      - epicure

networks:
  epicure:
    external: true

